# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('admission', models.CharField(max_length=32, verbose_name='准考证编码')),
                ('type', models.CharField(default='C1', max_length=32, verbose_name='类型')),
                ('code', models.CharField(max_length=18, verbose_name='身份证')),
                ('one', models.CharField(default='**', max_length=10, verbose_name='科目一')),
                ('two', models.CharField(default='**', max_length=10, verbose_name='科目二')),
                ('three', models.CharField(default='**', max_length=10, verbose_name='科目三')),
                ('four', models.CharField(default='**', max_length=10, verbose_name='科目四')),
            ],
        ),
    ]
